# Generated by Django 6.0.1 on 2026-01-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='课程名称')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('teacher', models.CharField(max_length=50, verbose_name='授课老师')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
