# Generated by Django 6.0.1 on 2026-02-01 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assignment_comment_studentsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '课程作业', 'verbose_name_plural': '课程作业'},
        ),
        migrations.AlterModelOptions(
            name='studentsubmission',
            options={'verbose_name': '学生作业提交', 'verbose_name_plural': '学生作业提交'},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='graded_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='打分时间'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.TextField(verbose_name='作业要求/知识点'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='answer',
            field=models.TextField(verbose_name='学生作答内容'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.assignment', verbose_name='对应作业'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='评分 (0-100)'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='is_graded',
        ),
    ]
